In [27]:
%load_ext autoreload
%autoreload 2

import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [42]:
from sandbox.haoran.hashing.bonus_evaluators.hashing_bonus_evaluator import HashingBonusEvaluator
from rllab.envs.box2d.car_parking_env import CarParkingEnv

env = CarParkingEnv()
hashing = HashingBonusEvaluator(env.spec,dim_key=10,bucket_sizes=None)

In [43]:
hashing.compute_keys(env.get_current_obs())

array([743, 743, 743, 743, 743, 743])

In [47]:
obs = np.asarray([0.1,0.2,-0.5,0.3,0.5])
print obs
obs = np.cast['int']((obs + 1) * 0.5 * 255.0)
print obs
binaries = np.sign(np.asarray(observations).dot(hashing.projection_matrix))
print binaries
keys = np.cast['int'](binaries.dot(hashing.mods_list)) % hashing.bucket_sizes
print keys

[ 0.1  0.2 -0.5  0.3  0.5]
[140 153  63 165 191]
[ 1.  1. -1. -1.  1.  1.  1. -1.  1.  1.]
[743 743 743 743 743 743]


In [51]:
(binaries+1).dot(hashing.mods_list)

array([ 1766.,  1766.,  1766.,  1766.,  1766.,  1766.])